# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle files instead.
# When configured as property, this is faster and disables in-process dex optimizations.
org.gradle.parallel=true
org.gradle.caching=true
# AndroidX package structure to make it clearer which packages are being used
android.useAndroidX=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not inherit from the library's dependencies,
# thereby reducing the size of the R class for that library
android.nonTransitiveRClass=true
android.enableJetifier=true
